apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-postgres
  template:
    metadata:
      labels:
        app: nginx-postgres
    spec:  # <-- `spec` should be here
      containers:
        - name: postgres
          image: postgres:15
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: "admin"
            - name: POSTGRES_PASSWORD
              value: "password"
            - name: POSTGRES_DB
              value: "mydatabase"

        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-postgres-service
spec:
  selector:
    app: nginx-postgres
  ports:
    - name: nginx
      protocol: TCP
      port: 80
      targetPort: 80
    - name: postgres
      protocol: TCP
      port: 5432
      targetPort: 5432
  type: NodePort  # Exposes the service within the cluster
